name: Deploy V2Ray with FRP (Root Fix)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      V2RAY_CONFIG_PATH: /usr/local/etc/v2ray
    steps:
      - name: Install V2Ray
        run: |
          # 安装 V2Ray（无需 sudo）
          bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
          
          # 下载并应用配置
          wget -O config_vmess_tcp.json https://raw.githubusercontent.com/mmxdxmm/v2ray-config/main/config_vmess_tcp.json
          mkdir -p $V2RAY_CONFIG_PATH && chmod 755 $V2RAY_CONFIG_PATH  # 显式设置目录权限
          cp config_vmess_tcp.json $V2RAY_CONFIG_PATH/config.json
          
          # 启动服务（后台运行）
          nohup /usr/local/bin/v2ray run -config $V2RAY_CONFIG_PATH/config.json > out.txt 2>&1 &

      - name: Deploy FRP Client
        run: |
          wget https://chmlfrp.cn/dw/ChmlFrp-0.51.2_240715_linux_amd64.tar.gz -O frp.tar.gz
          tar -xzvf frp.tar.gz
          chmod -R 755 ./frp_ChmlFrp-0.51.2_240715_linux_amd64
          cd frp_ChmlFrp-0.51.2_240715_linux_amd64
          ./frpc -u ${{ secrets.FRP_USER }} -p 115880
