name: Deploy2 V2Ray + FRP

on:
  workflow_dispatch:   # 保留手动触发能力
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次（UTC时间）

jobs:
  deploy:
    timeout-minutes: 359  # 超时时间，5小时59分钟
    runs-on: ubuntu-latest
    steps:
      - name: Setup V2Ray
        run: |
          # 解压并安装V2Ray
          wget -O v2ray.zip https://raw.githubusercontent.com/mmxdxmm/v2ray/refs/heads/main/v2ray-linux-64.zip
          unzip *.zip
          chmod -R 755 ./v2ray/*
          cd v2ray
          wget -O config.json https://raw.githubusercontent.com/mmxdxmm/v2ray-config/main/config.json
          
      - name: Deploy FRP Client
        run: |
          # 下载并解压FRP
          cd v2ray
          wget https://chmlfrp.cn/dw/ChmlFrp-0.51.2_240715_linux_amd64.tar.gz -O frp.tar.gz
          tar -xzvf frp.tar.gz
          chmod -R 755 ./ChmlFrp-0.51.2_240715_linux_amd64

      - name: run v2ray and frp
        run: |
          # 运行v2ray和frp
          cd v2ray
          ls
          ./v2ray run -config ./config.json  2>&1 | grep -v "Warning" & ./ChmlFrp-0.51.2_240715_linux_amd64/frpc -u ${{ secrets.FRP_USER }} -p 115880
